input.onButtonPressed(Button.A, function () {
    servos.P1.stop()
    basic.showNumber(0)
    basic.pause(500)
    servos.P1.setAngle(0)
    basic.pause(500)
    basic.showNumber(90)
    servos.P0.setAngle(90)
    basic.pause(500)
    basic.showNumber(180)
    servos.P1.setAngle(180)
})
basic.showString("SERVO TIME", 65)
basic.showIcon(IconNames.Heart)
